name: timeflux-hackathon
channels:
  - conda-forge
  - defaults
dependencies:
- pip>=19.3
- scikit-learn==0.22.0
- scipy==1.3.1
- pyglet
- pip:
  - git+https://github.com/timeflux/timeflux  # Timeflux core
  - git+https://github.com/timeflux/timeflux_example # Example plugin
  - git+https://github.com/timeflux/timeflux_dsp  # Timeflux Digital Signal Processing library
  - git+https://github.com/timeflux/timeflux_ui # Timeflux JavaScript library and UI
  - git+https://github.com/timeflux/timeflux_bitalino  # Bitalino driver
  - git+https://github.com/mindaffect/pymindaffectBCI # MindAffect library
