name: timeflux
channels:
  - conda-forge
  - defaults
dependencies:
- pip>=19.3
- sklearn
- pip:
  - git+https://github.com/timeflux/timeflux  # timeflux core
  - git+https://github.com/timeflux/timeflux_example # example pluggin
  - git+https://github.com/timeflux/timeflux_dsp  # pluggin for digital signal processing
  - git+https://github.com/timeflux/timeflux_ui # pluggin for timeflux JS UI