name: timeflux
channels:
  - conda-forge
  - defaults
dependencies:
- python>=3.7
- networkx>=2.4
- pyyaml>=5.1
- numpy>=1.17
- pandas>=0.25
- xarray>=0.14
- bottleneck>=1.3
- scipy>=1.3
- pyzmq>=18.1
- coloredlogs>=10.0
- pytables>=3.6
- jsonschema>=3.0
- python-dotenv>=0.10
- pytest>=5.3
- sphinx>=2.2
- sphinx_rtd_theme>=0.4
- python-graphviz>=0.13
- pip>=19.3
- pip:
  - pylsl>=1.13.1
  - python-osc>=1.7.0
  - git+https://github.com/timeflux/timeflux  # timeflux core
  - git+https://github.com/timeflux/timeflux_example # example pluggin
  - git+https://github.com/timeflux/timeflux_dsp  # pluggin for digital signal processing
  - git+https://github.com/timeflux/timeflux_ui # pluggin for timeflux JS UI
